name: BEANSTALK_DEPLOY_DEVELOP

on: 
  push:
      branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.env_to_promote_to }}
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    