name: BEANSTALK_DEPLOY_DEVELOP

on: 
  push:
      branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: develop
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - name: 'Deploy ${{ github.event.deployment.environment }}'
    - run: echo "success"


