name: BEANSTALK_DEPLOY_DEVELOP

on: 
  push:
      branches:
      - 

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/develop' }}
    environment: 
      name: develop
    environment: 
      name: review
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - name: Checkout source code
      run: echo "success"