name: BEANSTALK_DEPLOY_DEVELOP

on: 
  push:
      branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: develop
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1

on: 
  push:
      branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: review
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
  